// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedDatabase.Model;

namespace RedDatabase.Migrations
{
    [DbContext(typeof(RedDBContext))]
    partial class RedDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("RedDatabase.Model.RedFile", b =>
                {
                    b.Property<ulong>("RedFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Archive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RedFileId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("RedFileRedFile", b =>
                {
                    b.Property<ulong>("UsedByRedFileId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UsesRedFileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsedByRedFileId", "UsesRedFileId");

                    b.HasIndex("UsesRedFileId");

                    b.ToTable("RedFileRedFile");
                });

            modelBuilder.Entity("RedFileRedFile", b =>
                {
                    b.HasOne("RedDatabase.Model.RedFile", null)
                        .WithMany()
                        .HasForeignKey("UsedByRedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RedDatabase.Model.RedFile", null)
                        .WithMany()
                        .HasForeignKey("UsesRedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
