name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set the value
      id: step_one
      run: echo "action_state=yellow" >> $GITHUB_ENV
    - name: Use the value
      id: step_two
      run: echo "${{ env.action_state }}" # This will output 'yellow'
    
    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: .\WpfApp1\WpfApp1.csproj
  
    - name: Set Env
      id: set
      run: echo "VERSION=${{steps.get-version.outputs.version}}" >> $env:GITHUB_ENV
      env:
        VN: "${{steps.get-version.outputs.version}}"
    - run: echo "${{env.VERSION}}"
    - run: echo "${{steps.set.env.VN}}"
    - run: echo "${{steps.set.VN}}"
    - run: echo "${{env.VN}}"
    
    - name: Set the value
      run: echo "VERSION=${{steps.get-version.outputs.version}}" >> $env:GITHUB_ENV
    - run: echo "${{env.VERSION}}"
