name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: .\WpfApp1\WpfApp1.csproj
    - run: echo "${{steps.get-version.outputs.version}}"
    - name: Set the value
      env:
        VERSION: "${{steps.get-version.outputs.version}}"
      run: |
        echo echo "VERSION=${{steps.get-version.outputs.version}}" >> $GITHUB_ENV
    - run: echo "${{env.VERSION}}"
