name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get version
      uses: naminodarie/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: .\WpfApp1\WpfApp1.csproj
  
    - name: Set Env
      id: set
      run: echo "VERSION=${{steps.get-version.outputs.version}}" >> $env:GITHUB_ENV
      env:
        VN: "${{steps.get-version.outputs.version}}"
    - run: echo "${{steps.set.env.VN}}"
    - run: echo "${{steps.set.VN}}"
    - run: echo "${{env.VN}}"
    - run: echo "${{env.VERSION}}"
    - run: echo "PORTABLE=artifact1" >> $env:GITHUB_ENV
    - run: echo "INSTALLER=artifact2.txt" >> $env:GITHUB_ENV

    # Upload artifacts
    - name: Upload Artifact App
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.PORTABLE}}
        path: ./publish/full
    - name: Upload Artifact Installer
      uses: actions/upload-artifact@v2
      with:
        name: ${{env.INSTALLER}}
        path: .\publish\full\test\Mod\base\test.txt
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          ./publish/full
          .\publish\full\test\Mod\base\test.txt



