name: Testing

on:
  workflow_dispatch:

env:
  CHANGELOG_FILE: ${{ github.workspace }}-CHANGES.md
  STAGING_DIR: ${{ github.workspace }}-staging

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
        
    - name: Get Date
      run: |
        $date = Get-Date -Format "yyyy-MM-dd"
        echo "ISODATE=$date" >> $env:GITHUB_ENV
        
    - run: echo "VERSION=0.2.1-nightly.${{env.ISODATE}}" >> $env:GITHUB_ENV
    
    # tag this commit
    - name: Create Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: false
        custom_tag: ${{ env.VERSION }}
        tag_prefix: ""
        dry_run: true

    # echo
    - name: output step
      run: |
        echo new_tag: ${{ steps.tag_version.outputs.new_tag }}, new_version: ${{ steps.tag_version.outputs.new_version }}, previous_tag: ${{ steps.tag_version.outputs.previous_tag }}, previous_version: ${{ steps.tag_version.outputs.previous_version }}, release_type: ${{ steps.tag_version.outputs.release_type }}
    # echo
    - name: output step 2
      run: |
        echo new_tag: ${{ steps.tag_version.outputs.new_tag }}
        echo new_version: ${{ steps.tag_version.outputs.new_version }}
        echo previous_tag: ${{ steps.tag_version.outputs.previous_tag }}
        echo previous_version: ${{ steps.tag_version.outputs.previous_version }}
        echo release_type: ${{ steps.tag_version.outputs.release_type }}


    # echo
    - name: output
      run: |
        echo "This is a beta release so you may encounter bugs. Please report them. \n ${{ steps.tag_version.outputs.changelog }}"
        
    # RELEASE
    #- name: Release
    #  run: |
    #      gh release create ${{ steps.tag_version.outputs.new_version }} -n "${{ env.MESSAGE }}" --generate-notes -d
    #  env:
    #    MESSAGE: "This is a beta release so you may encounter bugs. Please report them. ${{ steps.tag_version.outputs.changelog }}"
    #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Install git-cliff
      uses: baptiste0928/cargo-install@v1
      with:
        crate: git-cliff
        version: "0.9"
  
    - name: Create the mod archive
      run: |
        mkdir ${{ env.STAGING_DIR }}
    
    - run: dir
    - name: git cliff
      run: git cliff --strip header
    - name: git-cliff help
      run: git-cliff --help
    - name: git-cliff
      run: git-cliff -v
        
    - name: Generate a changelog
      run: git-cliff --strip header -o ${{ env.CHANGELOG_FILE }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ env.CHANGELOG_FILE }}
        draft: true
        tag_name: ${{ steps.tag_version.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
