name: test_01

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: download
      run: gh release download --pattern '*.msix' --repo WolvenKit/WolvenKit.Installer
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - run: dir
