name: test_01

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest 
    
    steps:

    - name: dbg1
      run: |
        $gh = Get-Content '${{ github.event_path }}'
        $gh
        
    - name: dbg11
      run: |
        $gh = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
        $gh
        
    - name: dbg12
      run: |
        $gh = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
        $na = $gh.owner | Where-Object -Property avatar_url
        $na

    - name: dbg2
      run: |
        $gh = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
        $na = $gh.release.assets | Where-Object -Property name
        $na
