name: test_01

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest 
    
    steps:

    - name: dbg1
      run: |
        $gh = Get-Content '${{ github.event_path }}'
        $gh
        
    - name: dbg11
      run: |
        $gh = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
        $gh
        
    - name: dbg12
      run: |
        $gh = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
        $na = $gh.repository.description
        $na
        echo "DESCRIPTION=$na" >> $GITHUB_ENV
        
    - name: r1
      if: "${{ env.DESCRIPTION != '' }}"
      run: echo TEST
    
    - name: r2
      if: "${{ env.DESCRIPTION == '' }}"
      run: echo NULL
      
    - name: dbg13
      run: |
        $gh = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
        $na = $gh.repository.branches_url
        $na
        echo "DESCRIPTION2=$na" >> $GITHUB_ENV
        
    - name: r12
      if: "${{ env.DESCRIPTION2 != '' }}"
      run: echo TEST
    
    - name: r22
      if: "${{ env.DESCRIPTION2 == '' }}"
      run: echo NULL
        

